AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation workshop - Resources (uksb-1q9p31idr).

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Amazon EC2 Configuration
        Parameters:
          - InstanceType
    ParameterLabels:
      InstanceType:
        default: Type of EC2 Instance

Resources:
 Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref LatestAmiId

Parameters:

  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

  InstanceType:
    Description: Enter t2.micro or t2.small. Default is t2.micro.
    Type: String
    AllowedValues:
      - t2.micro
      - t2.small
    Default: t2.micro

Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
