AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation workshop - Resources (uksb-1q9p31idr).
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Amazon EC2 Configuration
      Parameters:
      - InstanceType
    ParameterLabels:
      InstanceType:
        default: Type of EC2 Instance

Mappings:
  RegionMap:
    us-east-1:
      ami: ami-0bb4d49541b2e75d4

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VpcId of your existing Virtual Private Cloud (VPC)
    ConstraintDescription: must be the VPC Id of an existing Virtual Private Cloud.
  SubnetId:
    Description: SubnetId of existing subnet for the primary network in your VPC.
    Type: AWS::EC2::Subnet::Id
  ListOfSecurityGroupIDs:
    Description: Array of security group ids
    Type: List<AWS::EC2::SecurityGroup::Id>
  RoleArnValue:
    Type: String
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  InstanceType:
    Description: Enter t2.micro or t2.small. Default is t2.micro.
    Type: String
    AllowedValues:
    - c5n.9xlarge
    - t2.micro
    Default: c5n.9xlarge

Resources:
  CDIlaunchtemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !FindInMap
          - RegionMap
          - !Ref 'AWS::Region'
          - ami
        InstanceType:
          Ref: InstanceType
        KeyName:
          Ref: KeyName
        NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          Groups: !Ref ListOfSecurityGroupIDs
          InterfaceType: efa
          SubnetId: !Ref SubnetId
        TagSpecifications:
        - ResourceType: instance
          Tags:
          - Key: Name
            Value: sbx-cdi
        UserData:
          Fn::Base64: |
            #!/usr/bin/env bash
            /opt/sbx/InstallSbxCDI/sanity_check
            PATH=/opt/amazon/efa/bin:$PATH /opt/sbx/InstallSbxCDI/aws-efa-installer/efa_test.sh
      LaunchTemplateName: sbx-cdi-1
